/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */ 
    double v[];
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdSuma = new javax.swing.JButton();
        cmdProducto = new javax.swing.JButton();
        cmdMayor = new javax.swing.JButton();
        cmdMenor = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("ejercicio1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 80, -1));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Longitud del vector");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel1.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 190, 50));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("menu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 40, -1));

        cmdCrear.setText("crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, -1));

        cmdManual.setText("llenado manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, -1));

        cmdAutomatico.setText("llenado automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, -1));

        cmdSuma.setText("sumatoria");
        cmdSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        cmdProducto.setText("productoria");
        cmdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProductoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        cmdMayor.setText("mayorelemento");
        cmdMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, -1));

        cmdMenor.setText("menorelemento");
        cmdMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenorActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        cmdMostrar.setText("mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, -1));

        cmdBorrar.setText("borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 330));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("resultados");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, -1, -1));

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 270));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLongitudActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        double llenado; 
       if(txtLongitud.getText().trim().isEmpty()){ 
         JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
         txtLongitud.requestFocusInWindow();
       }else{ 
           for (int i = 0; i < v.length; i++) {
          llenado=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemento en la posicion"+i)); 
          v[i]=llenado; 
               
           }
       }
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenorActionPerformed
      double menorelemento=99999999; 
    if(txtLongitud.getText().trim().isEmpty()){ 
      JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
      txtLongitud.requestFocusInWindow();
    }else{ 
        for (int i = 0; i < v.length; i++) {
           if(v[i]<menorelemento){ 
            menorelemento=v[i];
               
           }
            
        } 
        txtResultado.append("El numero menor es:"+menorelemento);
    }
    }//GEN-LAST:event_cmdMenorActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
       int longitud=0; 
     if(txtLongitud.getText().trim().isEmpty()){ 
         JOptionPane.showMessageDialog(this,"Ingrese valor de la longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
         txtLongitud.requestFocusInWindow();
     }else if(Integer.parseInt(txtLongitud.getText().trim())==0){
         JOptionPane.showMessageDialog(this,"La longitud del vector no puede ser cero","Error",JOptionPane.ERROR_MESSAGE); 
         txtLongitud.requestFocusInWindow(); 
         txtLongitud.selectAll();
    }else{ 
      longitud=Integer.parseInt(txtLongitud.getText()); 
          v=new double[longitud]; 
          JOptionPane.showMessageDialog(this,"Vector creado satisfactoriamente");
            }
     
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        char c=evt.getKeyChar(); 
      if(!Character.isDigit(c)){ 
        getToolkit().beep(); 
        evt.consume();
      }
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void cmdSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumaActionPerformed
        double acum=0; String res; 
      if(txtLongitud.getText().trim().isEmpty()){ 
        JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow();
      }else{ 
          for (int i = 0; i < v.length; i++) {
             acum=v[i]+acum;
          } 
        res=String.valueOf(acum); 
        txtResultado.setText("La sumatoria del vector es:");txtResultado.append(res);
          
      }
    }//GEN-LAST:event_cmdSumaActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       if(txtLongitud.getText().trim().isEmpty()){ 
        JOptionPane.showMessageDialog(this,"Ingrese longitud del vector","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow();
       }else{ 
           for (int i = 0; i < v.length; i++) {
              txtResultado.append(v[i]+"\n");
               
           }
       }
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProductoActionPerformed
        double acum=1;String res; 
       if(txtLongitud.getText().trim().isEmpty()){ 
        JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow();
       }else{ 
           for (int i = 0; i < v.length; i++) {
             acum=v[i]*acum;
           } 
           res=String.valueOf(acum); 
           txtResultado.setText("La productoria es: ");txtResultado.append(res);
            
       }
    }//GEN-LAST:event_cmdProductoActionPerformed

    private void cmdMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorActionPerformed
       double mayor=0; 
      if(txtLongitud.getText().trim().isEmpty()){ 
        JOptionPane.showMessageDialog(this,"Ingrese la longitud","Error",JOptionPane.ERROR_MESSAGE); 
        txtLongitud.requestFocusInWindow();
      }else{ 
          for (int i = 0; i < v.length; i++) {
             if(v[i]>mayor){ 
               mayor=v[i];
             }
              
          } 
          txtResultado.append("El numero mayor es:"+mayor); 
      }
    }//GEN-LAST:event_cmdMayorActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        double llenado,numero; 
      if(txtLongitud.getText().trim().isEmpty()){ 
       JOptionPane.showMessageDialog(this,"Ingrese la longitud,","Error",JOptionPane.ERROR_MESSAGE); 
       txtLongitud.requestFocusInWindow();
      }else{ 
        numero = Double.parseDouble (JOptionPane.showInputDialog(this, "Digite el numero hasta donde quiere el llenado automatico "));
           while (numero<v.length){ 
         JOptionPane.showMessageDialog(this,"Ingrese un numero que sea mayor a:"+v.length); 
         numero=Double.parseDouble(JOptionPane.showInputDialog("Digite el numero hasta donde quiere el llenado automatico"));
           } 
          for (int i = 0; i < v.length; i++) {
          llenado=(int) (Math.random()*numero+1); 
          v[i]=llenado;
              
          } 
          JOptionPane.showMessageDialog(this,"Vector llenado satisfactoriamente");
        
      }
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
      txtLongitud.setText(""); 
      txtResultado.setText(""); 
      txtLongitud.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdMayor;
    private javax.swing.JButton cmdMenor;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdProducto;
    private javax.swing.JButton cmdSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
